language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t msliwczynski/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true msliwczynski/docker-react npm run test

